### ISSUE TITLE
can u make it safe for Appstore?

### ISSUE THREAD

**Issue by yuedong56** [TimOliver/TOGlintyStringView#1]

**Comment by TimOliver** [comment]
No. I specified in the README the reasons for why it's not safe for the App Store.

The first point (i.e., the `allowsGroupBlending` property) could be sufficiently obfuscated that Apple wouldn't be able to detect it easily, but the second point (i.e. the `CAFilter` object) would be detected and rejected immediately.

There are of course different ways you could go about creating that 'stroked' layer, so you might be able to replicate the same effect using a more App Store-safe method, but the one in this example is definitely not App Store-safe.

This library is mainly just for educational reasons, _not_ for production iOS apps. Sorry! :)

**Comment by yuedong56** [comment]
ok , thx.
